/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ConviteSlugRouteImport } from './routes/convite/$slug'
import { Route as ConviteSlugConfirmarRouteImport } from './routes/convite/$slug/confirmar'
import { Route as PainelInvitationIdConvidadosRouteImport } from './routes/painel/$invitationId/convidados'
import { Route as PainelInvitationIdRsvpRouteImport } from './routes/painel/$invitationId/rsvp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteSlugRoute = ConviteSlugRouteImport.update({
  id: '/convite/$slug',
  path: '/convite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteSlugConfirmarRoute = ConviteSlugConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => ConviteSlugRoute,
} as any)
const PainelInvitationIdConvidadosRoute =
  PainelInvitationIdConvidadosRouteImport.update({
    id: '/$invitationId/convidados',
    path: '/$invitationId/convidados',
    getParentRoute: () => PainelRoute,
  } as any)
const PainelInvitationIdRsvpRoute = PainelInvitationIdRsvpRouteImport.update({
  id: '/$invitationId/rsvp',
  path: '/$invitationId/rsvp',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criar': typeof CriarRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/convite/$slug': typeof ConviteSlugRouteWithChildren
  '/convite/$slug/confirmar': typeof ConviteSlugConfirmarRoute
  '/painel/$invitationId/convidados': typeof PainelInvitationIdConvidadosRoute
  '/painel/$invitationId/rsvp': typeof PainelInvitationIdRsvpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criar': typeof CriarRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/convite/$slug': typeof ConviteSlugRouteWithChildren
  '/convite/$slug/confirmar': typeof ConviteSlugConfirmarRoute
  '/painel/$invitationId/convidados': typeof PainelInvitationIdConvidadosRoute
  '/painel/$invitationId/rsvp': typeof PainelInvitationIdRsvpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criar': typeof CriarRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/convite/$slug': typeof ConviteSlugRouteWithChildren
  '/convite/$slug/confirmar': typeof ConviteSlugConfirmarRoute
  '/painel/$invitationId/convidados': typeof PainelInvitationIdConvidadosRoute
  '/painel/$invitationId/rsvp': typeof PainelInvitationIdRsvpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/criar'
    | '/login'
    | '/painel'
    | '/convite/$slug'
    | '/convite/$slug/confirmar'
    | '/painel/$invitationId/convidados'
    | '/painel/$invitationId/rsvp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/criar'
    | '/login'
    | '/painel'
    | '/convite/$slug'
    | '/convite/$slug/confirmar'
    | '/painel/$invitationId/convidados'
    | '/painel/$invitationId/rsvp'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/criar'
    | '/login'
    | '/painel'
    | '/convite/$slug'
    | '/convite/$slug/confirmar'
    | '/painel/$invitationId/convidados'
    | '/painel/$invitationId/rsvp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CriarRoute: typeof CriarRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  ConviteSlugRoute: typeof ConviteSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$slug': {
      id: '/convite/$slug'
      path: '/convite/$slug'
      fullPath: '/convite/$slug'
      preLoaderRoute: typeof ConviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$slug/confirmar': {
      id: '/convite/$slug/confirmar'
      path: '/confirmar'
      fullPath: '/convite/$slug/confirmar'
      preLoaderRoute: typeof ConviteSlugConfirmarRouteImport
      parentRoute: typeof ConviteSlugRoute
    }
    '/painel/$invitationId/convidados': {
      id: '/painel/$invitationId/convidados'
      path: '/$invitationId/convidados'
      fullPath: '/painel/$invitationId/convidados'
      preLoaderRoute: typeof PainelInvitationIdConvidadosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/$invitationId/rsvp': {
      id: '/painel/$invitationId/rsvp'
      path: '/$invitationId/rsvp'
      fullPath: '/painel/$invitationId/rsvp'
      preLoaderRoute: typeof PainelInvitationIdRsvpRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelInvitationIdConvidadosRoute: typeof PainelInvitationIdConvidadosRoute
  PainelInvitationIdRsvpRoute: typeof PainelInvitationIdRsvpRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelInvitationIdConvidadosRoute: PainelInvitationIdConvidadosRoute,
  PainelInvitationIdRsvpRoute: PainelInvitationIdRsvpRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

interface ConviteSlugRouteChildren {
  ConviteSlugConfirmarRoute: typeof ConviteSlugConfirmarRoute
}

const ConviteSlugRouteChildren: ConviteSlugRouteChildren = {
  ConviteSlugConfirmarRoute: ConviteSlugConfirmarRoute,
}

const ConviteSlugRouteWithChildren = ConviteSlugRoute._addFileChildren(
  ConviteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CriarRoute: CriarRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  ConviteSlugRoute: ConviteSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
